load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "AstTest",
    srcs = ["AstTest.kt"],
    deps = [
        "//:truth",
        "//pigen/ast/src/org/pigen/python/ast",
    ],
)
